[package]
name = "tui_chat"
version = "0.1.0"
edition = "2021"

[dependencies]
cursive = "0.20"
redis = { version = "0.24.0", features = ["tokio-comp", "streams"] }
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "sync",
] }

[[bin]]
name = "app"
